version: '3.8'

services:
  # PostgreSQL Database for FlowCatalyst
  postgres:
    image: postgres:16-alpine
    container_name: flowcatalyst-postgres
    environment:
      POSTGRES_DB: flowcatalyst
      POSTGRES_USER: flowcatalyst
      POSTGRES_PASSWORD: flowcatalyst
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowcatalyst"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL Database for Keycloak
  postgres-keycloak:
    image: postgres:16-alpine
    container_name: flowcatalyst-postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ElasticMQ (Local SQS)
  elasticmq:
    image: softwaremill/elasticmq:latest
    container_name: flowcatalyst-elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    command: ["-Dconfig.file=/opt/elasticmq.conf"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9324"]
      interval: 10s
      timeout: 5s
      retries: 3

  # ActiveMQ (Alternative message broker)
  activemq:
    image: apache/activemq-classic:6.1.3
    container_name: flowcatalyst-activemq
    environment:
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: admin
    ports:
      - "61616:61616"  # OpenWire
      - "8161:8161"    # Web Console
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161/"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak (Authentication)
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: flowcatalyst-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    command: start-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
  postgres_keycloak_data:
    driver: local
  keycloak_data:
    driver: local

networks:
  default:
    name: flowcatalyst-network
