version: '3.8'

services:
  elasticmq:
    image: softwaremill/elasticmq:latest
    container_name: flow-catalyst-elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    command: ["-Dconfig.file=/opt/elasticmq.conf"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9324"]
      interval: 10s
      timeout: 5s
      retries: 3
