# Quarkus Configuration

# Enable bean archive index at runtime for permission/role scanning
quarkus.arc.remove-unused-beans=false
quarkus.index-dependency.jandex.group-id=org.jboss
quarkus.index-dependency.jandex.artifact-id=jandex

# Always index all classes for annotation scanning
quarkus.index-dependency.platform.group-id=tech.flowcatalyst
quarkus.index-dependency.platform.artifact-id=flowcatalyst-platform

# Hibernate ORM - JSON column handling
# We use JSONB columns in the database but don't need Quarkus' REST JSON formatting
quarkus.hibernate-orm.mapping.format.global=ignore
